### PR TITLE
Change the shapely-polygon converters to use the exterior.xy to…

### LINKED ISSUE #5: NotImplemetedError shapely.polygon.xy
In convert.py (lines 57-69)

`@hookimpl(specname="convert")`
`def convert_shapely_polygon(value: object):`
`    if isinstance(value, shapely.Polygon):`
`        return dict(`
`            area=value.area,`
`            perimeter=value.length,`
`            height=value.bounds[3] - value.bounds[1],`
`            width=value.bounds[2] - value.bounds[0],`
`#            x=np.array(value.boundary.xy[0]),`
`#            y=np.array(value.boundary.xy[1]),`
`            x=np.array(value.exterior.coords.xy[0]),`
`            y=np.array(value.exterior.coords.xy[1]),`
`        )`

exterior.coords.xy should be used rather than boundary.xy

Taken from
https://answers.ros.org/question/321957/shapelygeometrypolygon-to-geometry_msgspolygonstamped-shapely-polygon-representation-in-rviz/

Please check whether this is the correct way to avoid the NotImplementedError.
Are there other functions that need to be changed?

### PR DESCRIPTION
**Pull request by RichardPfr**
…circumvent errors, for cases when the boundary is no linestring.

### CODE REVIEW

**Comment by ChRen95** [comment]
@RichardPfr please use the "closes" keyword as we can therefore combine pull request and issue. 
Closes #5.

**Review by ChRen95 — APPROVED** [review]

**Comment by ChRen95** [comment]
@RichardPfr please resolve and merge

**Comment by RichardPfr** [comment]
@axtimhaus made some changes to `main` in the commit 31690ea which prevent the automatic merge (to output `xy` and `coords` instead of `x` and `y`):
```
xy=np.array(value.boundary.xy),
coords=np.array(value.boundary.coords),
```

This still causes the errors as in #5 and could all just be changed to the following to complete the pull request:
```
xy=np.array(value.exterior.coords.xy),
coords=np.array(value.exterior.coords),
```

But in that commit @GRPlan also mentioned issues with that change. My Question is if I should still just make the changes as described in this comment?
Also to me the `coords` and `xy` columns of the df seem to contain the exactly same content, just in a different shape.

**Comment by ChRen95** [comment]
So how I see the changes made by @axtimhaus: He wanted to give the export in general more flexibility, as he is exporting more information. The difference of `xy` and `coords` is that the latter one is ordered.  I propose, you add the x as well as y values to the dictionary, so having all 4 options.

**Comment by axtimhaus** [comment]
The meaning of xy and coords is the same as in shapely. Xy gives you distinct arrays of the x and y values, whereas coords gives you a list of coordinate tuples.

**Review by axtimhaus — APPROVED** [review]

**Pull request merged**
